/**
 * The four CrowdSource moderation tables.
 *
 * Ported from `models/ModerationReport.ts`, `ModerationOutbox.ts`,
 * `ModerationEvent.ts` and `ModerationEnforcement.ts`. All empty in production,
 * and `CROWDSOURCE_ENABLED` is absent from both SSM and the live task
 * definition — so nothing has ever written to them.
 *
 * Read those four modules for what the pipeline MEANS. What is decided here, and
 * could not be decided there, is below.
 *
 * ## Two of these tables have a PRIMARY KEY that is not an id this package mints
 *
 * `CONVENTIONS.md` says a primary key is an ObjectId hex for a migrated row and
 * a uuid v7 for a new one, generated by `generatedId()`. `moderation_outbox` and
 * `moderation_events` deviate, deliberately, and the deviation is the mechanism
 * rather than a shortcut:
 *
 *  - **`moderation_outbox.id` is DETERMINISTIC** —
 *    `moderation:report.submit:<reportId>` or
 *    `moderation:decision.apply:<eventId>`, from `reportSubmitEventId` /
 *    `decisionApplyEventId`. Two concurrent submissions therefore converge on
 *    ONE row instead of queueing two deliveries, which is what keeps the
 *    CrowdSource-side idempotency key stable. A minted uuid would give each
 *    racer its own row and deliver the same report twice.
 *  - **`moderation_events.id` IS the webhook event id.** The primary key is the
 *    dedupe: a redelivery cannot insert a second row, so a claim cannot succeed
 *    twice. Minting an id here would delete the only thing the table does.
 *
 * Both are declared `text().primaryKey()` with NO default, so a caller that
 * forgets to supply one fails on the insert rather than silently getting a uuid
 * and losing the property the table exists for.
 *
 * ## `payload.decision` and `payload` stay opaque
 *
 * Both are `jsonb`, and both earn it under `CONVENTIONS.md`'s test: a decision
 * document is deliberately loose so a newer CrowdSource does not break an older
 * client, and it is validated against the published contract when it is READ,
 * not when it is stored. Projecting it into columns would drop whatever a newer
 * server added — including a finding the enforcement mapping may later need.
 * The rest of `payload` (`reportId`, `eventId`, `caseId`) has a closed shape and
 * is flattened into columns, so the jsonb holds only the part that is genuinely
 * shapeless.
 */

import { bigint, boolean, check, index, jsonb, pgTable, text, uniqueIndex } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { createdAt, generatedId, inList, timestamptz, updatedAt } from '@oxyhq/db';
import type {
  ModerationEnforcementAction,
  ModerationEnforcementMode,
  ModerationLocalStatus,
  ModerationReportedType,
} from '@homiio/shared-types';
import { REVIEW_MODERATION_STATUSES } from './reviews';

export const MODERATION_REPORTED_TYPES = [
  'property',
  'review',
  'eviction_case',
] as const satisfies readonly `${ModerationReportedType}`[];

export const MODERATION_LOCAL_STATUSES = [
  'received',
  'queued',
  'submitted',
  'delivery_failed',
  'closed',
] as const satisfies readonly ModerationLocalStatus[];

export const MODERATION_ENFORCEMENT_ACTIONS = [
  'none',
  'restrict',
  'restore',
  'flag_for_review',
  'unflag',
  'manual_review',
] as const satisfies readonly ModerationEnforcementAction[];

export const MODERATION_ENFORCEMENT_MODES = [
  'observe',
  'manual',
  'automatic',
] as const satisfies readonly ModerationEnforcementMode[];

export const MODERATION_OUTBOX_KINDS = ['report.submit', 'decision.apply'] as const;
export const MODERATION_OUTBOX_STATUSES = [
  'pending',
  'processing',
  'processed',
  'dead_letter',
] as const;
export const MODERATION_EVENT_STATES = ['claimed', 'queued', 'ignored'] as const;

export const moderationReports = pgTable(
  'moderation_reports',
  {
    id: generatedId(),

    reportedType: text({ enum: MODERATION_REPORTED_TYPES }).notNull(),
    /**
     * The reported object's id — a `properties.id`, `reviews.id` or
     * `eviction_cases.id`, decided by `reported_type`.
     *
     * NO foreign key, and it never gets one. Two reasons, and either alone would
     * be enough: a single column cannot reference three tables (the permanent
     * case `images.entity_id` is also in), and this row must OUTLIVE the object
     * it names — `listing_reports` and `eviction_reports` both CASCADE away with
     * their subject, and this is the table that keeps what was delivered and
     * decided about it after the ad was reaped.
     */
    reportedId: text().notNull(),
    /**
     * The reporter's Oxy account.
     *
     * Mongo named the field `reporter`. Renamed to match `listing_reports` and
     * `eviction_reports`, which hold the same fact under
     * `reporter_oxy_user_id` — and, more than cosmetics, to bring it inside
     * `isOxyAccountColumn`, so the foreign-key gate classifies it instead of
     * skipping a column whose name says nothing about what it holds. The table is
     * empty, so the rename costs one backfill mapping entry.
     */
    reporterOxyUserId: text().notNull(),
    /**
     * The reason as the REPORTER picked it, in the vocabulary of the surface
     * they picked it on — `ListingReportReason` OR `ReviewReportReason`.
     *
     * NO CHECK, and this is the case where a union of two closed sets is the
     * wrong constraint rather than a missing one. The model stores the claim RAW
     * and translates it into a universal allegation code at delivery, precisely
     * so the mapping stays a versioned interpretation that can be corrected. A
     * CHECK over today's union of the two vocabularies would freeze a third,
     * synthetic set that no surface actually offers, and it would reject a
     * reason a NEW report surface adds before this table hears about it.
     */
    reason: text().notNull(),
    /** Stored at the SOURCE surface's limit and truncated to the contract's at delivery. */
    details: text(),

    localStatus: text({ enum: MODERATION_LOCAL_STATUSES }).notNull().default('received'),
    /** Why there is no durable route to CrowdSource, when `local_status` says so. */
    localStatusReason: text(),

    // ── The CrowdSource side. Every one of these is a foreign SERVICE's key. ──
    crowdSourceReportId: text(),
    crowdSourceCaseId: text(),
    /** Set when CrowdSource merged this report into an existing case. */
    crowdSourceMerged: boolean(),
    submittedAt: timestamptz(),

    // ── The decision CACHE. Never the source of truth; overwritten by a later revision. ──
    decisionId: text(),
    decisionRevision: bigint({ mode: 'number' }),
    decisionOutcome: text(),
    decisionStatus: text(),
    decidedAt: timestamptz(),

    enforcedAction: text({ enum: MODERATION_ENFORCEMENT_ACTIONS }),
    enforcedAt: timestamptz(),

    /** SHA-256 of the exact material that was sent for review. */
    contentSnapshotHash: text(),
    /** Last delivery failure, truncated. Never carries reported material. */
    lastDeliveryError: text(),

    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    /**
     * One report per reporter per object — the rule both existing surfaces
     * already enforce their own way, expressed once where a read cannot race it.
     */
    uniqueIndex('moderation_reports_reporter_object_key').on(
      table.reporterOxyUserId,
      table.reportedType,
      table.reportedId,
    ),
    /** The reconciliation sweep scans by delivery state, OLDEST first. */
    index('moderation_reports_local_status_created_idx').on(table.localStatus, table.createdAt),
    /**
     * "What has been reported about this object", scoped by the discriminator.
     * Mongo indexed `reportedId` ALONE, which is ambiguous across three nouns —
     * a `properties.id` and a `reviews.id` are both 24-char hex.
     */
    index('moderation_reports_object_idx').on(table.reportedType, table.reportedId),
    // Mongo's standalone `{ reporter: 1 }` and `{ localStatus: 1 }` are the
    // leading prefixes of the two indexes above and are not ported.
    index('moderation_reports_case_id_idx')
      .on(table.crowdSourceCaseId)
      .where(sql`${table.crowdSourceCaseId} is not null`),
    check(
      'moderation_reports_reported_type_check',
      sql`${table.reportedType} in (${sql.raw(inList(MODERATION_REPORTED_TYPES))})`,
    ),
    check(
      'moderation_reports_local_status_check',
      sql`${table.localStatus} in (${sql.raw(inList(MODERATION_LOCAL_STATUSES))})`,
    ),
    check(
      'moderation_reports_enforced_action_check',
      sql`${table.enforcedAction} in (${sql.raw(inList(MODERATION_ENFORCEMENT_ACTIONS))})`,
    ),
    /** `min: 1` from the schema — revision 0 is not a revision. */
    check(
      'moderation_reports_decision_revision_check',
      sql`${table.decisionRevision} is null or ${table.decisionRevision} >= 1`,
    ),
  ],
);

/**
 * `moderation_outbox` — the durable record of moderation work that has to
 * happen and has not happened yet.
 *
 * Singular, like `billing`: this is one queue, and `moderation_outboxes` would
 * read as several. `CONVENTIONS.md` records the mass-noun exception to the
 * plural rule.
 */
export const moderationOutbox = pgTable(
  'moderation_outbox',
  {
    /** DETERMINISTIC and caller-supplied — see the module header. */
    id: text().primaryKey().notNull(),

    kind: text({ enum: MODERATION_OUTBOX_KINDS }).notNull(),

    // ── payload, flattened except for the genuinely opaque half ──
    /**
     * The local report, for `report.submit`.
     *
     * A real foreign key with CASCADE: a submission job for a report that no
     * longer exists is work with no subject. Safe, unlike the `event_id` below,
     * because `moderation_reports` carries no expiry — nothing deletes one.
     */
    reportId: text().references(() => moderationReports.id, { onDelete: 'cascade' }),
    /**
     * The inbound webhook event, for `decision.apply`.
     *
     * NO foreign key, and this one is a deliberate refusal rather than an
     * impossibility. `moderation_events` is under its OWN expiry sweep with the
     * same 90-day retention as this table, and two independent sweeps have no
     * ordering between them: CASCADE would let the event sweep delete
     * unprocessed decision work, and RESTRICT would make the event sweep fail on
     * its first batch. Either way one table's housekeeping would decide the
     * other's correctness. The pairing is recoverable without a constraint —
     * `decisionApplyEventId` derives this id from the event's own.
     */
    eventId: text(),
    /** The CrowdSource case. A foreign service's key. */
    caseId: text(),
    /** The decision exactly as CrowdSource published it. Opaque; see the header. */
    decision: jsonb(),

    status: text({ enum: MODERATION_OUTBOX_STATUSES }).notNull().default('pending'),
    attempts: bigint({ mode: 'number' }).notNull().default(0),
    availableAt: timestamptz().notNull(),
    /** The lease. Claims are `FOR UPDATE SKIP LOCKED` plus an owner check. */
    leaseOwner: text(),
    leaseUntil: timestamptz(),
    lastError: text(),
    processedAt: timestamptz(),
    /** Retention ceiling, so a stalled dispatcher cannot make this unbounded. */
    expiresAt: timestamptz().notNull(),

    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    // Due work and expired claims are two separate bounded scans.
    index('moderation_outbox_due_idx').on(table.status, table.availableAt, table.createdAt),
    index('moderation_outbox_lease_idx').on(table.status, table.leaseUntil, table.createdAt),
    /** The expiry sweep's range scan. Registered in `db/expiry.ts`. */
    index('moderation_outbox_expires_at_idx').on(table.expiresAt),
    check(
      'moderation_outbox_kind_check',
      sql`${table.kind} in (${sql.raw(inList(MODERATION_OUTBOX_KINDS))})`,
    ),
    check(
      'moderation_outbox_status_check',
      sql`${table.status} in (${sql.raw(inList(MODERATION_OUTBOX_STATUSES))})`,
    ),
    check('moderation_outbox_attempts_check', sql`${table.attempts} >= 0`),
    /**
     * A lease is a pair. `leaseOwner` without `leaseUntil` is a claim that never
     * expires — a row no other dispatcher may ever take, which is how a single
     * crashed task stalls the whole queue silently.
     */
    check(
      'moderation_outbox_lease_pair_check',
      sql`(${table.leaseOwner} is null) = (${table.leaseUntil} is null)`,
    ),
  ],
);

/**
 * `moderation_events` — every webhook event CrowdSource has delivered here.
 *
 * Two jobs on purpose: the primary key IS the dedupe, and the row is the audit
 * trail of what a third party told this deployment to do.
 */
export const moderationEvents = pgTable(
  'moderation_events',
  {
    /** The CrowdSource event id — the dedupe. See the module header. */
    id: text().primaryKey().notNull(),

    /** Kept OPEN: an unknown type is recorded and ignored, never rejected. */
    type: text(),
    caseId: text(),
    /** The event's data exactly as delivered. Opaque; see the header. */
    payload: jsonb(),
    state: text({ enum: MODERATION_EVENT_STATES }).notNull().default('claimed'),
    receivedAt: timestamptz().notNull(),
    queuedAt: timestamptz(),
    expiresAt: timestamptz().notNull(),

    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    index('moderation_events_case_id_idx')
      .on(table.caseId)
      .where(sql`${table.caseId} is not null`),
    /** The expiry sweep's range scan. Registered in `db/expiry.ts`. */
    index('moderation_events_expires_at_idx').on(table.expiresAt),
    /** Operational: what arrived recently, and what never got past `claimed`. */
    index('moderation_events_state_received_idx').on(table.state, table.receivedAt),
    check(
      'moderation_events_state_check',
      sql`${table.state} in (${sql.raw(inList(MODERATION_EVENT_STATES))})`,
    ),
    /** `queued_at` exists exactly when the event reached `queued`. */
    check(
      'moderation_events_queued_at_check',
      sql`(${table.state} = 'queued') = (${table.queuedAt} is not null)`,
    ),
  ],
);

/**
 * `moderation_enforcements` — what Homiio did about a decision, one row per
 * action.
 *
 * The unique index below IS the idempotency key, and it is the whole mechanism:
 * a redelivered webhook, a reclaimed outbox lease and a manual replay all try to
 * insert the same row and only the first can.
 */
export const moderationEnforcements = pgTable(
  'moderation_enforcements',
  {
    id: generatedId(),

    /** CrowdSource's decision, and its revision. Foreign service keys. */
    decisionId: text().notNull(),
    decisionRevision: bigint({ mode: 'number' }).notNull(),
    action: text({ enum: MODERATION_ENFORCEMENT_ACTIONS }).notNull(),

    caseId: text().notNull(),
    /** Homiio's own noun (`property`, `review`). Never a CrowdSource resource id. */
    subjectType: text().notNull(),
    subjectId: text().notNull(),

    outcome: text().notNull(),
    recommendedAction: text(),
    /** Why this action, in words an operator can read. Never reported material. */
    reason: text().notNull(),

    mode: text({ enum: MODERATION_ENFORCEMENT_MODES }).notNull(),
    /** `false` for every action in `observe` mode — which is the point of the mode. */
    applied: boolean().notNull().default(false),
    appliedAt: timestamptz(),
    skippedReason: text(),

    /**
     * `previousState`, flattened — what to put back on a reversal.
     *
     * A nested path with no defaults, so it never materializes and both columns
     * are nullable. That nullability carries meaning here rather than merely
     * following the rule: only an action that CHANGED state records one, so NULL
     * is "there is nothing to put back".
     */
    previousStatePropertyModerationRestricted: boolean(),
    previousStateReviewModerationStatus: text({ enum: REVIEW_MODERATION_STATUSES }),

    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    /**
     * The idempotency key.
     *
     * `revision` is IN it for a reason of its own: a correction is a new revision
     * that supersedes the old one, so the `restore` it asks for is a different
     * action from the `restrict` that came before and must be allowed to happen —
     * while still being impossible to apply twice itself. Drop `revision` and an
     * upheld appeal can never put a listing back.
     */
    uniqueIndex('moderation_enforcements_decision_action_key').on(
      table.decisionId,
      table.decisionRevision,
      table.action,
    ),
    /** "What has been done to this object", newest first. */
    index('moderation_enforcements_subject_created_idx').on(
      table.subjectType,
      table.subjectId,
      sql`${table.createdAt} desc`,
    ),
    index('moderation_enforcements_case_id_idx').on(table.caseId),
    check(
      'moderation_enforcements_action_check',
      sql`${table.action} in (${sql.raw(inList(MODERATION_ENFORCEMENT_ACTIONS))})`,
    ),
    check(
      'moderation_enforcements_mode_check',
      sql`${table.mode} in (${sql.raw(inList(MODERATION_ENFORCEMENT_MODES))})`,
    ),
    check(
      'moderation_enforcements_previous_review_status_check',
      sql`${table.previousStateReviewModerationStatus} in (${sql.raw(inList(REVIEW_MODERATION_STATUSES))})`,
    ),
    check('moderation_enforcements_decision_revision_check', sql`${table.decisionRevision} >= 1`),
    /**
     * `applied_at` exists exactly when the action was carried out.
     *
     * The distinction this table is built to preserve is between a plan that was
     * RECORDED and one that was EXECUTED — that is what makes `observe` mode an
     * audit rather than a silent no-op. An `applied` row with no timestamp, or a
     * timestamp on an unapplied one, erases exactly that distinction.
     */
    check(
      'moderation_enforcements_applied_at_check',
      sql`${table.applied} = (${table.appliedAt} is not null)`,
    ),
  ],
);
