/**
 * Default discover city lists per market — used when `LISTING_<MARKET>_CITIES` is unset.
 *
 * Production worker env should override these with the same (or larger) lists in
 * oxy-infra `homiio-listing-cities.tf`. Slugs match each portal's search URLs.
 */

import type { ListingMarket } from './cities';

/** Spain — provincial capitals + major metros (idealista / fotocasa / pisos slugs). */
export const DEFAULT_ES_CITIES: readonly string[] = [
  'madrid',
  'barcelona',
  'valencia',
  'sevilla',
  'zaragoza',
  'malaga',
  'murcia',
  'palma',
  'las-palmas-de-gran-canaria',
  'bilbao',
  'alicante',
  'cordoba',
  'valladolid',
  'vigo',
  'gijon',
  'hospitalet-de-llobregat',
  'vitoria-gasteiz',
  'la-coruna',
  'granada',
  'elche',
  'oviedo',
  'badalona',
  'cartagena',
  'terrassa',
  'jerez-de-la-frontera',
  'sabadell',
  'mostoles',
  'pamplona',
  'fuenlabrada',
  'almeria',
  'leganes',
  'san-sebastian',
  'santander',
  'castellon-de-la-plana',
  'burgos',
  'albacete',
  'alcorcon',
  'getafe',
  'salamanca',
  'logrono',
  'huelva',
  'badajoz',
  'tarragona',
  'lleida',
  'marbella',
  'leon',
  'cadiz',
  'dos-hermanas',
  'parla',
  'mataro',
  'torrejon-de-ardoz',
  'alcobendas',
  'reus',
  'ourense',
  'telde',
  'barakaldo',
  'lugo',
  'santiago-de-compostela',
  'caceres',
  'lorca',
  'coslada',
  'talavera-de-la-reina',
  'el-ejido',
  'cornella-de-llobregat',
  'avila',
  'palencia',
  'guadalajara',
  'ceuta',
  'melilla',
];

/** United Kingdom — major cities (Rightmove typeahead labels). */
export const DEFAULT_GB_CITIES: readonly string[] = [
  'London',
  'Manchester',
  'Birmingham',
  'Leeds',
  'Glasgow',
  'Sheffield',
  'Bradford',
  'Edinburgh',
  'Liverpool',
  'Bristol',
  'Cardiff',
  'Coventry',
  'Leicester',
  'Nottingham',
  'Newcastle upon Tyne',
  'Southampton',
  'Brighton',
  'Plymouth',
  'Reading',
  'Derby',
  'Wolverhampton',
  'Northampton',
  'Norwich',
  'Luton',
  'Bolton',
  'Bournemouth',
  'Swindon',
  'Swansea',
  'Southend-on-Sea',
  'Middlesbrough',
  'Sunderland',
  'Milton Keynes',
  'Peterborough',
  'York',
  'Oxford',
  'Cambridge',
  'Ipswich',
  'Slough',
  'Gloucester',
  'Exeter',
  'Bath',
  'Cheltenham',
  'Stoke-on-Trent',
  'Hull',
  'Aberdeen',
  'Dundee',
  'Stirling',
  'Inverness',
  'Belfast',
  'Derry',
];

/** United States — top MSAs (`City, ST` for realtor / HotPads / Redfin). */
export const DEFAULT_US_CITIES: readonly string[] = [
  'New York, NY',
  'Los Angeles, CA',
  'Chicago, IL',
  'Houston, TX',
  'Phoenix, AZ',
  'Philadelphia, PA',
  'San Antonio, TX',
  'San Diego, CA',
  'Dallas, TX',
  'San Jose, CA',
  'Austin, TX',
  'Jacksonville, FL',
  'Fort Worth, TX',
  'Columbus, OH',
  'Charlotte, NC',
  'San Francisco, CA',
  'Indianapolis, IN',
  'Seattle, WA',
  'Denver, CO',
  'Washington, DC',
  'Boston, MA',
  'El Paso, TX',
  'Nashville, TN',
  'Detroit, MI',
  'Oklahoma City, OK',
  'Portland, OR',
  'Las Vegas, NV',
  'Memphis, TN',
  'Louisville, KY',
  'Baltimore, MD',
  'Milwaukee, WI',
  'Albuquerque, NM',
  'Tucson, AZ',
  'Fresno, CA',
  'Sacramento, CA',
  'Mesa, AZ',
  'Kansas City, MO',
  'Atlanta, GA',
  'Omaha, NE',
  'Colorado Springs, CO',
  'Raleigh, NC',
  'Long Beach, CA',
  'Virginia Beach, VA',
  'Miami, FL',
  'Oakland, CA',
  'Minneapolis, MN',
  'Tampa, FL',
  'Tulsa, OK',
  'Arlington, TX',
  'New Orleans, LA',
  'Wichita, KS',
  'Cleveland, OH',
  'Bakersfield, CA',
  'Aurora, CO',
  'Anaheim, CA',
  'Honolulu, HI',
  'Santa Ana, CA',
  'Riverside, CA',
  'Corpus Christi, TX',
  'Lexington, KY',
  'Henderson, NV',
  'Stockton, CA',
  'Saint Paul, MN',
  'Cincinnati, OH',
  'St. Louis, MO',
  'Pittsburgh, PA',
  'Greensboro, NC',
  'Anchorage, AK',
  'Plano, TX',
  'Lincoln, NE',
  'Orlando, FL',
  'Irvine, CA',
  'Newark, NJ',
  'Durham, NC',
  'Chula Vista, CA',
  'Toledo, OH',
  'Fort Wayne, IN',
  'St. Petersburg, FL',
  'Laredo, TX',
  'Jersey City, NJ',
  'Chandler, AZ',
  'Madison, WI',
  'Lubbock, TX',
  'Scottsdale, AZ',
  'Reno, NV',
  'Buffalo, NY',
  'Gilbert, AZ',
  'Glendale, AZ',
  'North Las Vegas, NV',
  'Winston-Salem, NC',
  'Chesapeake, VA',
  'Norfolk, VA',
  'Fremont, CA',
  'Garland, TX',
  'Irving, TX',
  'Hialeah, FL',
  'Richmond, VA',
  'Boise, ID',
  'Spokane, WA',
  'Baton Rouge, LA',
];

/** Germany — major cities (ImmobilienScout24 / Immowelt slugs). */
export const DEFAULT_DE_CITIES: readonly string[] = [
  'berlin',
  'hamburg',
  'muenchen',
  'koeln',
  'frankfurt',
  'stuttgart',
  'duesseldorf',
  'dortmund',
  'essen',
  'leipzig',
  'bremen',
  'dresden',
  'hannover',
  'nuernberg',
  'duisburg',
  'bochum',
  'wuppertal',
  'bielefeld',
  'bonn',
  'muenster',
  'karlsruhe',
  'mannheim',
  'augsburg',
  'wiesbaden',
  'gelsenkirchen',
  'moenchengladbach',
  'braunschweig',
  'chemnitz',
  'kiel',
  'aachen',
  'halle',
  'magdeburg',
  'freiburg',
  'krefeld',
  'luebeck',
  'oberhausen',
  'erfurt',
  'mainz',
  'rostock',
  'kassel',
  'hagen',
  'saarbruecken',
  'potsdam',
  'hamm',
  'ludwigshafen',
  'oldenburg',
  'leverkusen',
  'osnabrueck',
  'solingen',
  'heidelberg',
  'herne',
  'neuss',
  'darmstadt',
  'paderborn',
  'regensburg',
  'ingolstadt',
  'wuerzburg',
  'fuerth',
  'wolfsburg',
  'offenbach',
  'ulm',
  'heilbronn',
  'pforzheim',
  'goettingen',
  'bottrop',
  'recklinghausen',
  'reutlingen',
  'koblenz',
  'bremerhaven',
  'remscheid',
  'bergisch-gladbach',
  'jena',
  'erlangen',
  'trier',
  'moers',
  'siegen',
  'hildesheim',
  'salzgitter',
];

/** France — major cities (SeLoger / Leboncoin labels). */
export const DEFAULT_FR_CITIES: readonly string[] = [
  'Paris',
  'Lyon',
  'Marseille',
  'Toulouse',
  'Nice',
  'Nantes',
  'Strasbourg',
  'Montpellier',
  'Bordeaux',
  'Lille',
  'Rennes',
  'Reims',
  'Saint-Etienne',
  'Toulon',
  'Le Havre',
  'Grenoble',
  'Dijon',
  'Angers',
  'Nimes',
  'Villeurbanne',
  'Clermont-Ferrand',
  'Le Mans',
  'Aix-en-Provence',
  'Brest',
  'Tours',
  'Amiens',
  'Limoges',
  'Metz',
  'Perpignan',
  'Besancon',
  'Orleans',
  'Rouen',
  'Mulhouse',
  'Caen',
  'Nancy',
  'Argenteuil',
  'Montreuil',
  'Saint-Denis',
  'Roubaix',
];

/** Italy — major cities (idealista.it / immobiliare.it slugs). */
export const DEFAULT_IT_CITIES: readonly string[] = [
  'roma',
  'milano',
  'napoli',
  'torino',
  'palermo',
  'genova',
  'bologna',
  'firenze',
  'bari',
  'catania',
  'venezia',
  'verona',
  'messina',
  'padova',
  'trieste',
  'brescia',
  'parma',
  'taranto',
  'prato',
  'modena',
  'reggio-calabria',
  'reggio-emilia',
  'perugia',
  'livorno',
  'ravenna',
  'cagliari',
  'foggia',
  'rimini',
  'salerno',
  'ferrara',
  'sassari',
  'latina',
  'monza',
  'bergamo',
  'forli',
  'trento',
  'vicenza',
  'terni',
  'bolzano',
  'novara',
  'piacenza',
  'ancona',
  'udine',
  'lecce',
  'pesaro',
  'laquila',
  'alessandria',
  'catanzaro',
];

/** Romania — major cities (Storia / Imobiliare.ro slugs). */
export const DEFAULT_RO_CITIES: readonly string[] = [
  'bucuresti',
  'cluj-napoca',
  'timisoara',
  'iasi',
  'constanta',
  'craiova',
  'brasov',
  'galati',
  'ploiesti',
  'oradea',
  'braila',
  'arad',
  'pitesti',
  'sibiu',
  'bacau',
  'targu-mures',
  'baia-mare',
  'buzau',
  'botosani',
  'satu-mare',
];

/** Argentina — Zonaprop / Navent slugs. */
export const DEFAULT_AR_CITIES: readonly string[] = [
  'capital-federal',
  'cordoba',
  'rosario',
  'mendoza',
  'la-plata',
  'mar-del-plata',
  'san-miguel-de-tucuman',
  'salta',
  'santa-fe',
  'corrientes',
  'posadas',
  'neuquen',
  'bahia-blanca',
  'resistencia',
  'parana',
  'formosa',
  'san-juan',
  'san-luis',
  'catamarca',
  'la-rioja',
  'rio-cuarto',
  'villa-mercedes',
  'concordia',
  'trelew',
  'comodoro-rivadavia',
];

/** Mexico — Lamudi / Propiedades slugs. */
export const DEFAULT_MX_CITIES: readonly string[] = [
  'ciudad-de-mexico',
  'guadalajara',
  'monterrey',
  'puebla',
  'tijuana',
  'leon',
  'juarez',
  'zapopan',
  'merida',
  'san-luis-potosi',
  'aguascalientes',
  'queretaro',
  'morelia',
  'hermosillo',
  'saltillo',
  'culiacan',
  'chihuahua',
  'villahermosa',
  'reynosa',
  'cancun',
  'toluca',
  'veracruz',
  'xalapa',
  'oaxaca',
  'cuernavaca',
  'tampico',
  'durango',
  'mazatlan',
  'ensenada',
];

/** Ecuador — Plusvalía / MercadoLibre slugs. */
export const DEFAULT_EC_CITIES: readonly string[] = [
  'quito',
  'guayaquil',
  'cuenca',
  'santo-domingo',
  'machala',
  'manta',
  'portoviejo',
  'ambato',
  'riobamba',
  'loja',
  'esmeraldas',
  'ibarra',
  'latacunga',
  'babahoyo',
];

/** Colombia — MercadoLibre / Metrocuadrado slugs. */
export const DEFAULT_CO_CITIES: readonly string[] = [
  'bogota-dc',
  'medellin',
  'cali',
  'barranquilla',
  'cartagena',
  'bucaramanga',
  'cucuta',
  'pereira',
  'santa-marta',
  'ibague',
  'manizales',
  'villavicencio',
  'pasto',
  'monteria',
  'neiva',
  'armenia',
  'popayan',
  'sincelejo',
  'valledupar',
  'tunja',
];

/** Chile — MercadoLibre slugs. */
export const DEFAULT_CL_CITIES: readonly string[] = [
  'region-metropolitana',
  'valparaiso',
  'biobio',
  'araucania',
  'los-lagos',
  'coquimbo',
  'ohiggins',
  'maule',
  'antofagasta',
  'tarapaca',
  'atacama',
  'aysen',
  'magallanes',
  'los-rios',
  'nuble',
  'arica-y-parinacota',
];

/** Peru — MercadoLibre slugs. */
export const DEFAULT_PE_CITIES: readonly string[] = [
  'lima',
  'arequipa',
  'trujillo',
  'chiclayo',
  'piura',
  'cusco',
  'chimbote',
  'huancayo',
  'iquitos',
  'tacna',
  'cajamarca',
  'pucallpa',
  'sullana',
  'huanuco',
  'ayacucho',
  'tarapoto',
  'puno',
  'juliaca',
  'ica',
  'cuzco',
];

/** Portugal — Idealista.pt slugs. */
export const DEFAULT_PT_CITIES: readonly string[] = [
  'lisboa',
  'porto',
  'braga',
  'coimbra',
  'faro',
  'aveiro',
  'setubal',
  'leiria',
  'viseu',
  'funchal',
];

/** Canada — Realtor.ca city labels. */
export const DEFAULT_CA_CITIES: readonly string[] = [
  'Toronto',
  'Vancouver',
  'Montreal',
  'Calgary',
  'Edmonton',
  'Ottawa',
  'Winnipeg',
  'Quebec City',
  'Hamilton',
  'Kitchener',
];

/** Australia — realestate.com.au suburbs. */
export const DEFAULT_AU_CITIES: readonly string[] = [
  'Sydney',
  'Melbourne',
  'Brisbane',
  'Perth',
  'Adelaide',
  'Gold Coast',
  'Canberra',
  'Newcastle',
  'Wollongong',
  'Hobart',
];

/** UAE — Bayut city slugs. */
export const DEFAULT_AE_CITIES: readonly string[] = [
  'dubai',
  'abu-dhabi',
  'sharjah',
  'ajman',
  'ras-al-khaimah',
];

/** Ireland — Daft.ie / MyHome city labels. */
export const DEFAULT_IE_CITIES: readonly string[] = [
  'Dublin',
  'Cork',
  'Galway',
  'Limerick',
  'Waterford',
  'Drogheda',
  'Dundalk',
  'Swords',
  'Bray',
  'Navan',
];

/** Belgium — Immoweb city labels. */
export const DEFAULT_BE_CITIES: readonly string[] = [
  'Brussels',
  'Antwerp',
  'Ghent',
  'Charleroi',
  'Liege',
  'Bruges',
  'Namur',
  'Leuven',
  'Mons',
  'Mechelen',
];

/** Poland — Otodom city slugs. */
export const DEFAULT_PL_CITIES: readonly string[] = [
  'warszawa',
  'krakow',
  'lodz',
  'wroclaw',
  'poznan',
  'gdansk',
  'szczecin',
  'bydgoszcz',
  'lublin',
  'katowice',
];

/** Netherlands — Funda city labels. */
export const DEFAULT_NL_CITIES: readonly string[] = [
  'Amsterdam',
  'Rotterdam',
  'The Hague',
  'Utrecht',
  'Eindhoven',
  'Groningen',
  'Tilburg',
  'Almere',
  'Breda',
  'Nijmegen',
];

/** Default discover cities per market. */
export const DEFAULT_MARKET_CITIES: Readonly<Record<ListingMarket, readonly string[]>> = {
  ES: DEFAULT_ES_CITIES,
  GB: DEFAULT_GB_CITIES,
  US: DEFAULT_US_CITIES,
  DE: DEFAULT_DE_CITIES,
  FR: DEFAULT_FR_CITIES,
  IT: DEFAULT_IT_CITIES,
  RO: DEFAULT_RO_CITIES,
  AR: DEFAULT_AR_CITIES,
  MX: DEFAULT_MX_CITIES,
  EC: DEFAULT_EC_CITIES,
  CO: DEFAULT_CO_CITIES,
  CL: DEFAULT_CL_CITIES,
  PE: DEFAULT_PE_CITIES,
  PT: DEFAULT_PT_CITIES,
  CA: DEFAULT_CA_CITIES,
  AU: DEFAULT_AU_CITIES,
  AE: DEFAULT_AE_CITIES,
  IE: DEFAULT_IE_CITIES,
  BE: DEFAULT_BE_CITIES,
  PL: DEFAULT_PL_CITIES,
  NL: DEFAULT_NL_CITIES,
};
