import { create } from 'zustand';
import { ExchangeMode, OfferingType } from '@homiio/shared-types';
import type { AvailabilityWindow } from '@homiio/shared-types';
import type { UploadedImage } from '@/services/imageUploadService';

export interface PropertyBasicInfo {
  // title removed - will be auto-generated by backend
  description: string;
  propertyType: string;
  bedrooms: number;
  bathrooms: number;
  squareFootage: number;
  yearBuilt?: number;
}

export interface PropertyLocation {
  address: string;

  // Canonical address fields
  number?: string; // Street number (replaces addressNumber)
  building_name?: string; // Building or complex name
  block?: string; // Block identifier
  entrance?: string; // Door/entrance identifier
  unit?: string; // Apartment/unit number (replaces addressLine2)
  subunit?: string; // Sub-apartment identifier
  floor?: number;
  showFloor?: boolean;
  district?: string; // District/area within city
  address_lines?: string[]; // Flexible address lines array
  po_box?: string; // Post office box
  reference?: string; // Reference landmark or identifier

  neighborhood?: string;
  city: string;
  state?: string; // Made optional for international support
  postal_code: string; // Renamed from zipCode
  country: string;
  countryCode?: string; // Added for international support
  latitude: number;
  longitude: number;
  availableFrom?: string;
  leaseTerm?: string;
  walkScore?: number;
  transitScore?: number;
  bikeScore?: number;
  proximityToTransport?: boolean;
  proximityToSchools?: boolean;
  proximityToShopping?: boolean;
}

/**
 * Per-offering pricing for the listing, keyed by the multi-select
 * {@link offerings}. A listing can be offered several ways at once (e.g.
 * "rent monthly + by night + sell"); the matching fields below are only
 * meaningful — and only submitted — when {@link offerings} includes the
 * corresponding {@link OfferingType}:
 *  - LONG_TERM_RENT → `monthlyRent` (+ `securityDeposit`/`applicationFee`/`lateFee`)
 *  - SHORT_TERM_RENT → `nightlyRate` (+ `cleaningFee`/`serviceFee`/`taxesPercent`/`minNights`/`maxNights`/`instantBook`)
 * `currency` is shared across the rent offerings. Sale/exchange sub-fields live
 * on {@link PropertyOffering}.
 */
export interface PropertyPricing {
  offerings: OfferingType[];
  currency: string;
  // Long-term (monthly) rent.
  monthlyRent: number;
  securityDeposit: number;
  applicationFee?: number;
  lateFee?: number;
  // Short-term (per-night) rent.
  nightlyRate: number;
  cleaningFee?: number;
  serviceFee?: number;
  taxesPercent?: number;
  minNights?: number;
  maxNights?: number;
  instantBook: boolean;
}

export interface PropertyAmenities {
  selectedAmenities: string[];
}

export interface PropertyRules {
  petsAllowed: boolean;
  smokingAllowed: boolean;
  partiesAllowed: boolean;
  guestsAllowed: boolean;
  maxGuests?: number;
}

export interface PropertyMedia {
  images: UploadedImage[];
  videos?: UploadedImage[];
}

export interface PropertyColivingFeatures {
  sharedSpaces: boolean;
  communityEvents: boolean;
  sharedSpacesList?: string[];
  otherFeatures?: string;
}

/**
 * Sale + exchange sub-fields for the listing. The sale fields are only
 * meaningful when {@link PropertyPricing.offerings} includes
 * {@link OfferingType.SALE} and are submitted under the property `sale` block;
 * the exchange fields likewise apply only when `offerings` includes
 * {@link OfferingType.EXCHANGE} and are submitted under the property `exchange`
 * block.
 */
export interface PropertyOffering {
  salePrice?: number;
  saleCurrency?: string;
  chainStatus?: string;
  isPriceReduced?: boolean;
  // Exchange (home swap / free hosting) sub-fields.
  exchangeMode: ExchangeMode;
  exchangeAvailabilityWindows: AvailabilityWindow[];
  exchangeMinStay?: number;
  exchangeMaxStay?: number;
  exchangeWelcomeNote?: string;
  exchangeLanguages: string[];
  exchangeMealsIncluded: boolean;
  exchangeRequiresReciprocity: boolean;
}

export interface CreatePropertyFormData {
  basicInfo: PropertyBasicInfo;
  location: PropertyLocation;
  pricing: PropertyPricing;
  amenities: PropertyAmenities;
  rules: PropertyRules;
  media: PropertyMedia;
  colivingFeatures: PropertyColivingFeatures;
  offering: PropertyOffering;
}

export type CreatePropertyFormSection = keyof CreatePropertyFormData;

/**
 * Build a fresh, fully-defaulted form tree.
 *
 * This is a FACTORY (not a shared constant) so every nested array
 * (`offerings`, `exchangeAvailabilityWindows`, `exchangeLanguages`, image
 * lists, …) is brand-new on every call. A shared object literal would hand the
 * same nested refs to the initial state AND every `resetForm`, so an in-place
 * mutation on one listing could leak into the next. A new listing defaults to
 * the long-term-rent offering until the host opts into more; `exchangeMode`
 * defaults to the most permissive `both` (accepts a swap or a hosting request).
 */
export function createDefaultFormData(): CreatePropertyFormData {
  return {
    basicInfo: {
      // title removed - will be auto-generated by backend
      description: '',
      propertyType: '',
      bedrooms: 1,
      bathrooms: 1,
      squareFootage: 0,
      yearBuilt: undefined,
    },
    location: {
      address: '',
      number: undefined,
      building_name: undefined,
      block: undefined,
      entrance: undefined,
      unit: undefined,
      subunit: undefined,
      floor: undefined,
      showFloor: undefined,
      district: undefined,
      address_lines: undefined,
      po_box: undefined,
      reference: undefined,
      neighborhood: undefined,
      city: '',
      state: '',
      postal_code: '',
      country: 'US',
      countryCode: 'US',
      latitude: 41.38723, // Default to Barcelona
      longitude: 2.16538, // Default to Barcelona
      availableFrom: undefined,
      leaseTerm: undefined,
      walkScore: undefined,
      transitScore: undefined,
      bikeScore: undefined,
      proximityToTransport: undefined,
      proximityToSchools: undefined,
      proximityToShopping: undefined,
    },
    pricing: {
      offerings: [OfferingType.LONG_TERM_RENT],
      currency: 'USD',
      monthlyRent: 0,
      securityDeposit: 0,
      applicationFee: 0,
      lateFee: 0,
      nightlyRate: 0,
      cleaningFee: 0,
      serviceFee: 0,
      taxesPercent: 0,
      minNights: undefined,
      maxNights: undefined,
      instantBook: false,
    },
    amenities: {
      selectedAmenities: [],
    },
    rules: {
      petsAllowed: false,
      smokingAllowed: false,
      partiesAllowed: false,
      guestsAllowed: false,
      maxGuests: undefined,
    },
    media: {
      images: [],
      videos: [],
    },
    colivingFeatures: {
      sharedSpaces: false,
      communityEvents: false,
      sharedSpacesList: [],
      otherFeatures: '',
    },
    offering: {
      exchangeMode: ExchangeMode.BOTH,
      exchangeAvailabilityWindows: [],
      exchangeLanguages: [],
      exchangeMealsIncluded: false,
      exchangeRequiresReciprocity: false,
    },
  };
}

// Create Property Form State Interface
interface CreatePropertyFormState {
  // Data
  formData: CreatePropertyFormData;
  currentStep: number;
  isDirty: boolean;

  // Loading states
  isLoading: boolean;
  error: string | null;

  // Actions
  setFormData: <S extends CreatePropertyFormSection>(
    section: S,
    data: Partial<CreatePropertyFormData[S]>,
  ) => void;
  updateFormField: <S extends CreatePropertyFormSection>(
    section: S,
    field: keyof CreatePropertyFormData[S],
    value: CreatePropertyFormData[S][keyof CreatePropertyFormData[S]],
  ) => void;
  /**
   * Advance to the next step, clamped to `maxStep` (the last index of the
   * ACTIVE step list). The cap is passed in by the wizard so it always tracks
   * the resolved flow length (which varies with the selected offerings),
   * instead of a hardcoded literal.
   */
  nextStep: (maxStep: number) => void;
  prevStep: () => void;
  setCurrentStep: (step: number) => void;
  setIsDirty: (dirty: boolean) => void;
  resetForm: () => void;
  setLoading: (loading: boolean) => void;
  setError: (error: string | null) => void;
  clearError: () => void;
}

export const useCreatePropertyFormStore = create<CreatePropertyFormState>()((set) => ({
  // Initial state
  formData: createDefaultFormData(),
  currentStep: 0,
  isDirty: false,
  isLoading: false,
  error: null,

  // Actions
  setFormData: (section, data) =>
    set((state) => ({
      formData: {
        ...state.formData,
        [section]: { ...state.formData[section], ...data },
      },
      isDirty: true,
    })),
  updateFormField: (section, field, value) =>
    set((state) => ({
      formData: {
        ...state.formData,
        [section]: {
          ...state.formData[section],
          [field]: value,
        },
      },
      isDirty: true,
    })),
  nextStep: (maxStep) =>
    set((state) => ({
      // Clamp to the last index of the active flow (derived by the caller from
      // the resolved step list length), never a hardcoded literal — the flow
      // grows when the host adds an offering (long-term/nightly/sale/exchange).
      currentStep: Math.min(state.currentStep + 1, maxStep),
    })),
  prevStep: () =>
    set((state) => ({
      currentStep: Math.max(state.currentStep - 1, 0), // 0 is the min step
    })),
  setCurrentStep: (step) => set({ currentStep: step }),
  setIsDirty: (dirty) => set({ isDirty: dirty }),
  resetForm: () =>
    set(() => ({
      // Reuse the same factory as the initial state so reset re-seeds fresh
      // nested arrays — the next listing never inherits the previous one's
      // offerings / exchange windows (no shared array refs across resets).
      formData: createDefaultFormData(),
      currentStep: 0,
      isDirty: false,
      error: null,
    })),
  setLoading: (loading) => set({ isLoading: loading }),
  setError: (error) => set({ error }),
  clearError: () => set({ error: null }),
}));

// Selector hooks for easier access
export const useCreatePropertyFormSelectors = () => {
  const formData = useCreatePropertyFormStore((state) => state.formData);
  const currentStep = useCreatePropertyFormStore((state) => state.currentStep);
  const isDirty = useCreatePropertyFormStore((state) => state.isDirty);
  const isLoading = useCreatePropertyFormStore((state) => state.isLoading);
  const error = useCreatePropertyFormStore((state) => state.error);

  return {
    formData,
    currentStep,
    isDirty,
    isLoading,
    error,
  };
};
