import { create } from 'zustand';
import { createJSONStorage, persist } from 'zustand/middleware';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { ExchangeMode, OfferingType } from '@homiio/shared-types';
import type { AvailabilityWindow } from '@homiio/shared-types';
import type { UploadedImage } from '@/services/imageUploadService';

export interface PropertyBasicInfo {
  // title removed - will be auto-generated by backend
  description: string;
  propertyType: string;
  bedrooms: number;
  bathrooms: number;
  squareFootage: number;
  yearBuilt?: number;
}

export interface PropertyLocation {
  address: string;

  // Canonical address fields
  number?: string; // Street number (replaces addressNumber)
  building_name?: string; // Building or complex name
  block?: string; // Block identifier
  entrance?: string; // Door/entrance identifier
  unit?: string; // Apartment/unit number (replaces addressLine2)
  subunit?: string; // Sub-apartment identifier
  floor?: number;
  showFloor?: boolean;
  district?: string; // District/area within city
  address_lines?: string[]; // Flexible address lines array
  po_box?: string; // Post office box
  reference?: string; // Reference landmark or identifier

  neighborhood?: string;
  city: string;
  state?: string; // Made optional for international support
  postal_code: string; // Renamed from zipCode
  country: string;
  countryCode?: string; // Added for international support
  latitude: number;
  longitude: number;
  availableFrom?: string;
  leaseTerm?: string;
  walkScore?: number;
  transitScore?: number;
  bikeScore?: number;
  proximityToTransport?: boolean;
  proximityToSchools?: boolean;
  proximityToShopping?: boolean;
}

/**
 * Per-offering pricing for the listing, keyed by the multi-select
 * {@link offerings}. A listing can be offered several ways at once (e.g.
 * "rent monthly + by night + sell"); the matching fields below are only
 * meaningful — and only submitted — when {@link offerings} includes the
 * corresponding {@link OfferingType}:
 *  - LONG_TERM_RENT → `monthlyRent` (+ `securityDeposit`/`applicationFee`/`lateFee`)
 *  - SHORT_TERM_RENT → `nightlyRate` (+ `cleaningFee`/`serviceFee`/`taxesPercent`/`minNights`/`maxNights`/`instantBook`)
 * `currency` is shared across the rent offerings. Sale/exchange sub-fields live
 * on {@link PropertyOffering}.
 */
export interface PropertyPricing {
  offerings: OfferingType[];
  currency: string;
  // Long-term (monthly) rent.
  monthlyRent: number;
  securityDeposit: number;
  applicationFee?: number;
  lateFee?: number;
  // Short-term (per-night) rent.
  nightlyRate: number;
  cleaningFee?: number;
  serviceFee?: number;
  taxesPercent?: number;
  minNights?: number;
  maxNights?: number;
  instantBook: boolean;
}

export interface PropertyAmenities {
  selectedAmenities: string[];
}

export interface PropertyRules {
  petsAllowed: boolean;
  smokingAllowed: boolean;
  partiesAllowed: boolean;
  guestsAllowed: boolean;
  maxGuests?: number;
}

export interface PropertyMedia {
  images: UploadedImage[];
  videos?: UploadedImage[];
}

export interface PropertyColivingFeatures {
  sharedSpaces: boolean;
  communityEvents: boolean;
  sharedSpacesList?: string[];
  otherFeatures?: string;
}

/**
 * Sale + exchange sub-fields for the listing. The sale fields are only
 * meaningful when {@link PropertyPricing.offerings} includes
 * {@link OfferingType.SALE} and are submitted under the property `sale` block;
 * the exchange fields likewise apply only when `offerings` includes
 * {@link OfferingType.EXCHANGE} and are submitted under the property `exchange`
 * block.
 */
export interface PropertyOffering {
  salePrice?: number;
  saleCurrency?: string;
  chainStatus?: string;
  isPriceReduced?: boolean;
  // Exchange (home swap / free hosting) sub-fields.
  exchangeMode: ExchangeMode;
  exchangeAvailabilityWindows: AvailabilityWindow[];
  exchangeMinStay?: number;
  exchangeMaxStay?: number;
  exchangeWelcomeNote?: string;
  exchangeLanguages: string[];
  exchangeMealsIncluded: boolean;
  exchangeRequiresReciprocity: boolean;
}

export interface CreatePropertyFormData {
  basicInfo: PropertyBasicInfo;
  location: PropertyLocation;
  pricing: PropertyPricing;
  amenities: PropertyAmenities;
  rules: PropertyRules;
  media: PropertyMedia;
  colivingFeatures: PropertyColivingFeatures;
  offering: PropertyOffering;
}

export type CreatePropertyFormSection = keyof CreatePropertyFormData;

/**
 * Build a fresh, fully-defaulted form tree.
 *
 * This is a FACTORY (not a shared constant) so every nested array
 * (`offerings`, `exchangeAvailabilityWindows`, `exchangeLanguages`, image
 * lists, …) is brand-new on every call. A shared object literal would hand the
 * same nested refs to the initial state AND every `resetForm`, so an in-place
 * mutation on one listing could leak into the next. A new listing defaults to
 * the long-term-rent offering until the host opts into more; `exchangeMode`
 * defaults to the most permissive `both` (accepts a swap or a hosting request).
 */
export function createDefaultFormData(): CreatePropertyFormData {
  return {
    basicInfo: {
      // title removed - will be auto-generated by backend
      description: '',
      propertyType: '',
      bedrooms: 1,
      bathrooms: 1,
      squareFootage: 0,
      yearBuilt: undefined,
    },
    location: {
      address: '',
      number: undefined,
      building_name: undefined,
      block: undefined,
      entrance: undefined,
      unit: undefined,
      subunit: undefined,
      floor: undefined,
      showFloor: undefined,
      district: undefined,
      address_lines: undefined,
      po_box: undefined,
      reference: undefined,
      neighborhood: undefined,
      city: '',
      state: '',
      postal_code: '',
      country: 'US',
      countryCode: 'US',
      latitude: 41.38723, // Default to Barcelona
      longitude: 2.16538, // Default to Barcelona
      availableFrom: undefined,
      leaseTerm: undefined,
      walkScore: undefined,
      transitScore: undefined,
      bikeScore: undefined,
      proximityToTransport: undefined,
      proximityToSchools: undefined,
      proximityToShopping: undefined,
    },
    pricing: {
      offerings: [OfferingType.LONG_TERM_RENT],
      currency: 'USD',
      monthlyRent: 0,
      securityDeposit: 0,
      applicationFee: 0,
      lateFee: 0,
      nightlyRate: 0,
      cleaningFee: 0,
      serviceFee: 0,
      taxesPercent: 0,
      minNights: undefined,
      maxNights: undefined,
      instantBook: false,
    },
    amenities: {
      selectedAmenities: [],
    },
    rules: {
      petsAllowed: false,
      smokingAllowed: false,
      partiesAllowed: false,
      guestsAllowed: false,
      maxGuests: undefined,
    },
    media: {
      images: [],
      videos: [],
    },
    colivingFeatures: {
      sharedSpaces: false,
      communityEvents: false,
      sharedSpacesList: [],
      otherFeatures: '',
    },
    offering: {
      exchangeMode: ExchangeMode.BOTH,
      exchangeAvailabilityWindows: [],
      exchangeLanguages: [],
      exchangeMealsIncluded: false,
      exchangeRequiresReciprocity: false,
    },
  };
}

// Create Property Form State Interface
interface CreatePropertyFormState {
  // Data
  formData: CreatePropertyFormData;
  currentStep: number;
  isDirty: boolean;
  /**
   * The listing the form was hydrated from in edit mode, or `null` for a new
   * listing. The create screen resets a form that still holds an edited
   * listing, so "Create" never starts from somebody's existing home.
   */
  editingPropertyId: string | null;
  /**
   * The local draft this form saves to (`utils/propertyDrafts`), or `null`
   * until it is first saved. Kept with the form — and across a restart — so
   * leaving the screen, or losing the process, keeps saving over the same
   * draft instead of leaving a trail of half-listings behind.
   */
  draftId: string | null;
  /**
   * Whether the persisted form has been read back yet.
   *
   * AsyncStorage is asynchronous, so for the first renders after launch this
   * store holds DEFAULTS that look exactly like "nothing in progress". Anything
   * that would overwrite the form — resetting it, hydrating it from the server
   * in edit mode — has to wait for this, or it discards the work it was
   * supposed to restore.
   */
  hasHydrated: boolean;

  // Loading states
  isLoading: boolean;
  error: string | null;

  // Actions
  setFormData: <S extends CreatePropertyFormSection>(
    section: S,
    data: Partial<CreatePropertyFormData[S]>,
  ) => void;
  updateFormField: <S extends CreatePropertyFormSection>(
    section: S,
    field: keyof CreatePropertyFormData[S],
    value: CreatePropertyFormData[S][keyof CreatePropertyFormData[S]],
  ) => void;
  /**
   * Advance to the next step, clamped to `maxStep` (the last index of the
   * ACTIVE step list). The cap is passed in by the wizard so it always tracks
   * the resolved flow length (which varies with the selected offerings),
   * instead of a hardcoded literal.
   */
  nextStep: (maxStep: number) => void;
  setCurrentStep: (step: number) => void;
  setIsDirty: (dirty: boolean) => void;
  setEditingPropertyId: (id: string | null) => void;
  setDraftId: (id: string | null) => void;
  /**
   * Replaces the whole form with a resumed draft, at the step it was left on.
   *
   * `step` used to be hardcoded to 0, so resuming a nearly-finished listing put
   * the host back on "what kind of place is it?" — the work was there, the
   * place in the work was not.
   */
  loadForm: (formData: CreatePropertyFormData, draftId: string, step?: number) => void;
  resetForm: () => void;
  setLoading: (loading: boolean) => void;
  setError: (error: string | null) => void;
  clearError: () => void;
}

/**
 * AsyncStorage key for the live form. Versioned in the name as well as through
 * `persist`'s own `version`, so a shape change can never be read by the wrong
 * reader.
 */
export const CREATE_PROPERTY_FORM_PERSIST_KEY = 'homiio.create-property-form.v1';

/**
 * The publish wizard's form.
 *
 * ## Why this store is persisted and the others here are not
 *
 * It used to be a bare `create()`. Everything typed between two step
 * transitions — a description somebody spent ten minutes on — lived only in
 * memory, so backgrounding the app on a phone, or a reload on web, took it. The
 * drafts layer looked like it covered that and did not: it was written on step
 * ADVANCE, which is the one moment the current step's work is already behind
 * you.
 *
 * So the live form is written on every change, and `utils/propertyDrafts` keeps
 * its separate job — the named, listable draft the host can come back to. The
 * two are reconciled through `draftId`, which is persisted here: a session
 * restored after a crash is still working on the SAME draft, so finishing it
 * replaces that draft rather than adding a near-duplicate beside it.
 *
 * ## What crosses a restart, and what must not
 *
 * The allow-list below is deliberately short: the form, where the host was in
 * it, whether it has unsaved changes, and which listing (draft or edit) it
 * belongs to. `isLoading` and `error` are about a request that is long over by
 * the time the app starts again — restoring either would show a spinner nothing
 * will ever stop, or an error about a submit that no longer exists.
 */
export const useCreatePropertyFormStore = create<CreatePropertyFormState>()(
  persist(
    (set) => ({
      // Initial state
      formData: createDefaultFormData(),
      currentStep: 0,
      isDirty: false,
      editingPropertyId: null,
      draftId: null,
      hasHydrated: false,
      isLoading: false,
      error: null,

      // Actions
      setFormData: (section, data) =>
        set((state) => ({
          formData: {
            ...state.formData,
            [section]: { ...state.formData[section], ...data },
          },
          isDirty: true,
        })),
      updateFormField: (section, field, value) =>
        set((state) => ({
          formData: {
            ...state.formData,
            [section]: {
              ...state.formData[section],
              [field]: value,
            },
          },
          isDirty: true,
        })),
      nextStep: (maxStep) =>
        set((state) => ({
          // Clamp to the last index of the active flow (derived by the caller from
          // the resolved step list length), never a hardcoded literal — the flow
          // grows when the host adds an offering (long-term/nightly/sale/exchange).
          currentStep: Math.min(state.currentStep + 1, maxStep),
        })),
      setCurrentStep: (step) => set({ currentStep: step }),
      setIsDirty: (dirty) => set({ isDirty: dirty }),
      setEditingPropertyId: (id) => set({ editingPropertyId: id }),
      setDraftId: (id) => set({ draftId: id }),
      loadForm: (formData, draftId, step = 0) =>
        set({
          // Defaults first, so a draft saved before a section existed still loads
          // with every section present.
          formData: { ...createDefaultFormData(), ...formData },
          // The wizard clamps this to its own active step list, which varies with
          // the offerings the draft selected — so a step out of that list lands on
          // the last one rather than crashing.
          currentStep: step,
          isDirty: false,
          editingPropertyId: null,
          draftId,
          error: null,
        }),
      resetForm: () =>
        set(() => ({
          // Reuse the same factory as the initial state so reset re-seeds fresh
          // nested arrays — the next listing never inherits the previous one's
          // offerings / exchange windows (no shared array refs across resets).
          formData: createDefaultFormData(),
          currentStep: 0,
          isDirty: false,
          editingPropertyId: null,
          draftId: null,
          error: null,
        })),
      setLoading: (loading) => set({ isLoading: loading }),
      setError: (error) => set({ error }),
      clearError: () => set({ error: null }),
    }),
    {
      name: CREATE_PROPERTY_FORM_PERSIST_KEY,
      version: 1,
      storage: createJSONStorage(() => AsyncStorage),
      partialize: (state) => ({
        formData: state.formData,
        currentStep: state.currentStep,
        isDirty: state.isDirty,
        editingPropertyId: state.editingPropertyId,
        draftId: state.draftId,
      }),
      // Runs whether the read succeeded, failed or found nothing: the flag says
      // "the restore has been attempted", and a screen waiting on it must not
      // wait forever because storage was unavailable.
      onRehydrateStorage: () => () => {
        useCreatePropertyFormStore.setState({ hasHydrated: true });
      },
    },
  ),
);

// Selector hooks for easier access
export const useCreatePropertyFormSelectors = () => {
  const formData = useCreatePropertyFormStore((state) => state.formData);
  const currentStep = useCreatePropertyFormStore((state) => state.currentStep);
  const isDirty = useCreatePropertyFormStore((state) => state.isDirty);
  const isLoading = useCreatePropertyFormStore((state) => state.isLoading);
  const error = useCreatePropertyFormStore((state) => state.error);

  return {
    formData,
    currentStep,
    isDirty,
    isLoading,
    error,
  };
};
