import { requireOptionalNativeModule, type NativeModule } from 'expo';

/**
 * JS side of the local `HomiioWidgets` Expo module — Homiio's Android home-screen
 * widgets.
 *
 * The module is **Android-only and native-only**: a home-screen widget is a platform
 * surface with no iOS or web equivalent (iOS has WidgetKit, a different framework in a
 * different language), and because `android/` is generated by CNG it is present only in
 * builds made after this landed. So every export has to answer for a MISSING module
 * rather than only for a missing capability, which is why `requireOptionalNativeModule`
 * is used and its `null` is handled once here instead of at each call site.
 *
 * The surface is deliberately one function. A widget runs outside the app process — its
 * worker can fetch while the app is dead, and it can be placed before the app has ever
 * been opened — so it owns its data end to end in Kotlin: fetch, cache, render, deep
 * link. Anything mirrored here would be a second implementation of that path, correct
 * only for as long as both copies stayed in step.
 */

// `declare class`, not an interface: `NativeModule` is exported as the CONSTRUCTOR
// type, so only a class heritage clause yields the instance side. This is the shape
// create-expo-module generates.
declare class HomiioWidgetsNativeModule extends NativeModule {
  /**
   * Enqueue an immediate refresh of the listings widget. Resolves once the work is
   * queued, not once it has run.
   */
  refreshListings(): Promise<void>;
}

const nativeModule = requireOptionalNativeModule<HomiioWidgetsNativeModule>('HomiioWidgets');

/** Whether this build can host home-screen widgets at all. */
export const areHomeScreenWidgetsAvailable = nativeModule !== null;

/**
 * Ask the listings widget to fetch now.
 *
 * A no-op where the module is absent, and a no-op natively when no listings widget is on
 * the home screen — so callers never have to check either.
 */
export function refreshListingsWidget(): Promise<void> {
  return nativeModule?.refreshListings() ?? Promise.resolve();
}
